<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="2" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="10709" started-at="2022-01-15T16:52:46 IST" finished-at="2022-01-15T16:52:57 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="10709" started-at="2022-01-15T16:52:46 IST" finished-at="2022-01-15T16:52:57 IST">
      <class name="org.etsbytes.testcases.HomepageTest">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:org.etsbytes.testcases.HomepageTest@6121c9d6]" name="beforeSuite" is-config="true" duration-ms="13" started-at="2022-01-15T16:52:46 IST" finished-at="2022-01-15T16:52:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.etsbytes.testcases.HomepageTest@6121c9d6]" name="setUp" is-config="true" duration-ms="5483" started-at="2022-01-15T16:52:47 IST" finished-at="2022-01-15T16:52:52 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:org.etsbytes.testcases.HomepageTest@6121c9d6]" name="loginTest" duration-ms="2947" started-at="2022-01-15T16:52:52 IST" description="To check whether the user can login to askOmDch website" data-provider="getData" finished-at="2022-01-15T16:52:55 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [UnknowTitle] but found [Account – AskOmDch]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [UnknowTitle] but found [Account – AskOmDch]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at org.etsbytes.testcases.HomepageTest.loginTest(HomepageTest.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:org.etsbytes.testcases.HomepageTest@6121c9d6]" name="tearDown" is-config="true" duration-ms="714" started-at="2022-01-15T16:52:56 IST" finished-at="2022-01-15T16:52:56 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:org.etsbytes.testcases.HomepageTest@6121c9d6]" name="afterSuite" is-config="true" duration-ms="0" started-at="2022-01-15T16:52:58 IST" finished-at="2022-01-15T16:52:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- org.etsbytes.testcases.HomepageTest -->
      <class name="org.etsbytes.testcases.PaymentTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.etsbytes.testcases.PaymentTest@11758f2a]" name="setUp" is-config="true" duration-ms="5495" started-at="2022-01-15T16:52:47 IST" finished-at="2022-01-15T16:52:52 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="paymentTest(java.lang.String,java.lang.String)[pri:0, instance:org.etsbytes.testcases.PaymentTest@11758f2a]" name="paymentTest" duration-ms="3216" started-at="2022-01-15T16:52:52 IST" description="To verify the payment mode is working or not" data-provider="getData" finished-at="2022-01-15T16:52:55 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [UnknowTitle] but found [Account – AskOmDch]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [UnknowTitle] but found [Account – AskOmDch]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at org.etsbytes.testcases.PaymentTest.paymentTest(PaymentTest.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- paymentTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:org.etsbytes.testcases.PaymentTest@11758f2a]" name="tearDown" is-config="true" duration-ms="841" started-at="2022-01-15T16:52:56 IST" finished-at="2022-01-15T16:52:57 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.etsbytes.testcases.PaymentTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
